baseURL = "https://wangdaoping.pages.dev/"
languageCode = "en-us"
theme = "hyde"
title = "Daoping Wang"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 1

[[menu.main]]
name = "Data"
url = "/data/"
weight = 2

[[menu.main]]
name = "Citations"
url = "/citations/"
weight = 3
